### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by james2doyle**
Merge the latest `Develop` branch changes into the master.

### CODE REVIEW

**Comment by james2doyle** [comment]
When we get some more +1's on this, I will merge this in.

**Comment by Frodox** [comment]
It's hard to view `+4,489 −3,990` at once, but all individual commits are ok, so +1 from me :)

**Comment by kicken** [comment]
Has a +1 from me.  Looks good.

**Comment by NeoBlack** [comment]
@james2doyle I would like to have #285, #286 and #290 merged into develop before you merge develop into master. all three no-brainer or important for composer installations. can you please vote and merge this before make a new release?

**Comment by james2doyle** [comment]
The tests are failing because of the bumped PHP version requirement in Scrutinizer

**Comment by NeoBlack** [comment]
don't know how scrutinizer works, but running the stuff with PHP 5.4?

**Comment by NeoBlack** [comment]
the red travis looks like a temporary issue.

**Comment by james2doyle** [comment]
Is this all good now? Anyone not happy with this?

**Pull request merged**
