### PR TITLE
refactor url handling

### PR DESCRIPTION
**Pull request by Schlaefer**

### CODE REVIEW

**Comment by Schlaefer** [comment]
Last call for raising concerns before I merge this.

**Comment by Stijn-Flipper** [comment]
Did you consider this situation:

- `content/sub.md`
- `content/sub/index.md`

Both requests `/sub` and `/sub/` points _always_ to `content/sub.md`? As mentioned on discussion #192 those requests are in fact requesting for two different pages... It seems that your PR only solves the trailing slashes problem, which is the first half of the problem on the page duplicates.

**Comment by Schlaefer** [comment]
> Both requests /sub and /sub/ points always to content/sub.md? 

If both pages are present then:

- /sub → content/sub.md
- /sub/ → content/sub/index.md

Only if one page is missing it tries to resolve to the other one. If both are missing 404.

**Comment by Stijn-Flipper** [comment]
So it worked on your side? I always got `content/sub.md` for that particular case.

**Comment by Schlaefer** [comment]
> So it worked on your side? I always got content/sub.md for that particular case.

Does work here. Can you run the test cases?

**Comment by kicken** [comment]
I have been running with this patch for a couple days without noticing any issues.  I just did a quick manual test of the situation and it worked fine.  If both sub.md and sub/index.md existed they were treated as separate pages.  If only one existed it redirected as appropriate.

**Comment by Stijn-Flipper** [comment]
My bad, I was checking out the wrong commit, works also fine here :+1:

(The test cases also passed successfully)

**Pull request merged**
