### PR TITLE
Feature/fix74

### PR DESCRIPTION
**Pull request by Schlaefer**
Adds PHP 7.4 compatibility

### CODE REVIEW

**Comment by james2doyle** [comment]
Glad to see someone still using Phile. I don’t have any sites on it anymore unfortunately 😞

**Comment by Schlaefer** [comment]
@james2doyle  Such is OSS. ;-) I still have some properties running on it. Actually I started using it again recently on Raspberry Pi setups.

While node/js/vue/yadayada overrun the web-community, most non-PHP Phile-like solutions feel they reinvent the wheel without much benefit but more complexity. So I'm still in the game. And as long as there's no complete rewrite required I think I'll support Phile just for sentimental reason. It was fun and I learned a lot. :-)

**Comment by james2doyle** [comment]
Yeah I know what you mean. I switched my blog over to [Hugo](https://gohugo.io/) a while back but I think its actually harder to maintain now because Hugo keeps moving forward and changing things. So in hindsight it probably would have been better in something more stable

**Comment by Schlaefer** [comment]
@james2doyle Aaah, static page generators. Didn't even like the PHP ones back in the days. Never remembered the syntax and the existing setup was always broken after three full moons. ;)

Happy to see that you're still around. Nice that you chimed in! :+1:

**Pull request merged**
