### PR TITLE
remove composer version

### LINKED ISSUE #294: Can't install Phile 1.7.0 with composer
Please report your issue with the following information:

### Excpected behavior

Phile installs via composer by the officially encouraged command.

### Actual behavior

```bash
$ composer create-project --no-dev phile-cms/phile

Installing phile-cms/phile (1.6.0)
  - Installing phile-cms/phile (1.6.0)
    Loading from cache

Created project in /Users/siezi/Desktop/test_phile/phile
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phile-cms/plugin-installer-plugin 1.0.2 -> satisfiable by phile-cms/plugin-installer-plugin[1.0.2].
    - phile-cms/plugin-installer-plugin 1.0.2 requires composer-plugin-api 1.0.0 -> no matching package found.
```

### Steps to reproduce the behavior

run ```composer create-project --no-dev phile-cms/phile```

### Additional information

I just wanted to do check that 1.7 composer installation runs through but it failed. I believe it's related to removing the version information from composer.json in #286.

### PR DESCRIPTION
**Pull request by james2doyle**
[BUGFIX] Remove package version property

Fixes #294 I hope?

### CODE REVIEW

**Comment by james2doyle** [comment]
I'm guessing this failing is another issue with composer?

**Comment by james2doyle** [comment]
Hmm it seems to have passed now...

**Comment by james2doyle** [comment]
There must have been a bad merge somewhere along the way. Because the version was removed in a past commit: https://github.com/PhileCMS/Phile/commit/c913491ffd70a76574a5b285f96a61a48e5cd45f

**Comment by Schlaefer** [comment]
👍 

This should at least make packagist pick up the git tag. Let's see if everything else works too.

**Pull request merged**
