### PR TITLE
rename phile icon in error handler plugin, fix #211

### LINKED ISSUE #211: Phile icon is missing in errorHanlder in non-dev checkout
https://github.com/PhileCMS/Phile/blob/master/plugins/phile/errorHandler/Icon.png

probably filtered by #200

### PR DESCRIPTION
**Pull request by Schlaefer**
this is a weasel solution but it should do the job

### CODE REVIEW

**Comment by Stijn-Flipper** [comment]
:-1:

> You don't have to rename the file, instead just remove [this line from `.gitattributes`](https://github.com/PhileCMS/Phile/blob/develop/.gitattributes#L2).
> 
> I've added it to `.gitattributes` on PR #200 because I thought it was some leftover development file.

**Comment by Schlaefer** [comment]
> You don't have to rename the file, instead just remove this line

If we remove the line the icon file in the root is in again, and we don't need that.

PS: I guess the right solution is to prefix everything in gitattributes with a slash, but I was to lazy to test that.

**Comment by Stijn-Flipper** [comment]
Oh now I see. Yeah, prefixing it with a slash will do the job.

> but I was to lazy to test that.

Heh :p

**Comment by Schlaefer** [comment]
Let's merge this (no harm done) and #220 and after that a new PR adding a slash prefix to all the root files in .gitattributes (if that works, still have to test it :wink:).

**Comment by Stijn-Flipper** [comment]
> Let's merge this (no harm done) and #220 and after that a new PR adding a slash prefix to all the root files in .gitattributes (if that works, still have to test it ).

:+1:

**Pull request merged**
